/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#2f4c42",
        "error": "#ffb4ab",
        "secondary": "#dcc48f",
        "surface-container-lowest": "#00110c",
        "on-primary": "#003918",
        "inverse-primary": "#006d35",
        "surface-tint": "#00e475",
        "on-primary-fixed": "#00210b",
        "on-tertiary-fixed": "#022018",
        "outline": "#859585",
        "secondary-container": "#55451b",
        "surface-dim": "#021711",
        "surface-container-low": "#091f19",
        "primary-container": "#00e676",
        "inverse-surface": "#cfe8de",
        "on-secondary-container": "#cab37f",
        "on-primary-fixed-variant": "#005226",
        "on-secondary-fixed": "#251a00",
        "on-tertiary-container": "#3c5a4f",
        "outline-variant": "#3b4a3d",
        "on-surface": "#cfe8de",
        "primary": "#75ff9e",
        "on-error-container": "#ffdad6",
        "on-surface-variant": "#bacbb9",
        "on-secondary": "#3d2e06",
        "primary-fixed-dim": "#00e475",
        "tertiary-container": "#b0d0c2",
        "on-background": "#cfe8de",
        "background": "#021711",
        "tertiary": "#cbecde",
        "secondary-fixed": "#f9e0a8",
        "surface-container": "#0d231d",
        "surface-bright": "#283d36",
        "surface-container-high": "#182e27",
        "on-tertiary": "#19362c",
        "tertiary-fixed-dim": "#adcec0",
        "primary-fixed": "#62ff96",
        "surface": "#021711",
        "surface-container-highest": "#233932",
        "inverse-on-surface": "#1f352e",
        "on-primary-container": "#00612e",
        "error-container": "#93000a",
        "surface-variant": "#233932",
        "on-error": "#690005",
        "secondary-fixed-dim": "#dcc48f",
        "on-secondary-fixed-variant": "#55451b",
        "tertiary-fixed": "#c9eadc"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "24px",
        "full": "9999px"
      },
      spacing: {
        "margin-desktop": "80px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "gutter": "24px",
        "stack-sm": "8px",
        "section-gap": "120px",
        "margin-mobile": "20px",
        "container-max": "1200px"
      },
      fontFamily: {
        "headline-md": ["IBM Plex Sans Arabic"],
        "headline-lg-mobile": ["IBM Plex Sans Arabic"],
        "body-md": ["Outfit"],
        "body-lg": ["Outfit"],
        "label-sm": ["Outfit"],
        "headline-lg": ["IBM Plex Sans Arabic"]
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "52px", letterSpacing: "-0.02em", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
